# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20161204_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='time_recieved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
